services:
    tenolo_open_graph.manager:
        class: Tenolo\Bundle\OpenGraphBundle\Manager\MapManager

    tenolo_open_graph.renderer:
        class: Tenolo\Bundle\OpenGraphBundle\Renderer\OpenGraphRenderer

    tenolo_open_graph.twig_extension:
        class: Tenolo\Bundle\OpenGraphBundle\Twig\Extension\OpenGraphExtension
        arguments: ['@tenolo_open_graph.renderer']
        tags:
            - { name: twig.extension }
